#pragma once

#define MATRIX_ROWS 3
#define MATRIX_COLS 4

#define ENCODER_A_PINS { GP4 }
#define ENCODER_B_PINS { GP3 }

#define OLED_DISPLAY_128X32
#define OLED_DISPLAY_ADDRESS 0x3C

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7
#define I2C1_CLOCK_SPEED 50000
#define OLED_TIMEOUT 0   // Never turn off

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U